import {AppProps} from 'next/app';
import Head from 'next/head';
import '../styles/globals.css';

function MyApp({Component, pageProps}: AppProps): JSX.Element {
    return (
        <>
            <Head>
                <title>Udemy next project</title>
                <link rel="stylesheet"
                      href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;700&display=swap"/>
                <link rel="icon" href="/favicon.ico"/>
                <meta name="description" content="Generated by create next app"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
            </Head>
            <Component {...pageProps} />
        </>
    );
}

export default MyApp;
